#!/bin/sh

action="$(printf "Lock Screen\nQuit\nPower Off\nReboot\n" | shadow-dmenu -p "Choose an action")"

case "$action" in
	"Lock Screen") shadow-lock-screen;;
	"Quit") riverctl exit;;
	"Power Off") foot -a wmfloat sudo poweroff;;
	"Reboot") foot -a wmfloat sudo reboot;;
esac
